// <auto-generated />
using CategoryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CategoryApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241111144610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bánh kem, bánh kem bắp, bánh kem nhân mứt",
                            Name = "Bánh kem"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bánh mì, bánh quy, donut",
                            Name = "Bánh nướng"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bánh flan, bánh su kem, pudding ",
                            Name = "Bánh lạnh"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kem vani, kem đậu xanh, kem dâu, kem chuối",
                            Name = "Cà rem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
